"""SAP S/4HANA on-premise OData client backed by a BTP destination.

Generated by migrate-agent-to-cf runbook for PIVA agent.
Covers OP_PRODUCT_0002 (_ProductEWMWarehouse)
and OP_WHSEPHYSICALINVENTORYDOC_0001 (WarehousePhysicalInventoryDoc).
CF service bindings required in VCAP_SERVICES: destination, connectivity.
"""
from __future__ import annotations
import json, logging, os, time
from dataclasses import dataclass, field
from typing import Any, Optional
import httpx

logger = logging.getLogger(__name__)

DEFAULT_DESTINATION_NAME: str = os.environ.get("S4HANA_QVL_DESTINATION_NAME", "S4Hana_QVL")
DEFAULT_TIMEOUT_SECONDS: float = float(os.environ.get("S4HANA_QVL_TIMEOUT_SECONDS", "20.0"))
TOKEN_TTL: float = float(os.environ.get("DESTINATION_TOKEN_TTL", "600"))
DEST_CACHE_TTL: float = float(os.environ.get("DESTINATION_CACHE_TTL", "300"))
RESPONSE_ENVELOPE = "odata_v2"
CSRF_REQUIRED = True


def _vcap() -> dict[str, Any]:
    raw = os.environ.get("VCAP_SERVICES")
    if not raw:
        return {}
    try:
        return json.loads(raw)
    except Exception:
        logger.warning("VCAP_SERVICES is set but not valid JSON")
        return {}


def _first_binding(label: str) -> dict[str, Any] | None:
    bindings = _vcap().get(label) or []
    if not bindings:
        return None
    return (bindings[0] or {}).get("credentials") or {}


@dataclass
class Destination:
    url: str
    auth_type: str
    username: str | None = None
    password: str | None = None
    sap_client: str | None = None
    proxy_type: str = "Internet"
    additional: dict[str, str] = field(default_factory=dict)


@dataclass
class _CachedToken:
    value: str
    expires_at: float

    def expired(self) -> bool:
        return time.monotonic() >= self.expires_at


class _DestinationResolver:
    """Resolves BTP destinations; caches tokens and destination configs."""

    def __init__(self, timeout: float = DEFAULT_TIMEOUT_SECONDS) -> None:
        self._timeout = timeout
        self._xsuaa_token = None  # type: Optional[_CachedToken]
        self._proxy_token = None  # type: Optional[_CachedToken]
        self._dest_cache: dict[str, tuple] = {}

    async def _client_credentials_token(
        self, token_url: str, client_id: str, client_secret: str
    ) -> str:
        _ba = httpx.BasicAuth(client_id, client_secret)
        async with httpx.AsyncClient(timeout=self._timeout) as http:
            r = await http.post(
                token_url.rstrip("/") + "/oauth/token",
                data={"grant_type": "client_credentials"},
                auth=_ba,
                headers={"Accept": "application/json"},
            )
        r.raise_for_status()
        return r.json()["access_token"]

    async def _xsuaa_access_token(self) -> str:
        if self._xsuaa_token and not self._xsuaa_token.expired():
            return self._xsuaa_token.value
        creds = _first_binding("destination") or {}
        if not creds:
            raise RuntimeError(
                "No destination service binding found in VCAP_SERVICES. "
                "Bind proj-vector-destination-service to the app."
            )
        tok = await self._client_credentials_token(
            creds["url"], creds["clientid"], creds["clientsecret"]
        )
        _ct = object.__new__(_CachedToken)
        _ct.__dict__["value"] = tok
        _ct.__dict__["expires_at"] = time.monotonic() + TOKEN_TTL
        self._xsuaa_token = _ct
        return tok

    async def _connectivity_proxy_token(self) -> str:
        if self._proxy_token and not self._proxy_token.expired():
            return self._proxy_token.value
        creds = _first_binding("connectivity") or {}
        if not creds:
            raise RuntimeError(
                "Destination is OnPremise but no connectivity binding found. "
                "Bind proj-vector-connectivity-service to the app."
            )
        tok = await self._client_credentials_token(
            creds["token_service_url"], creds["clientid"], creds["clientsecret"]
        )
        _ct = object.__new__(_CachedToken)
        _ct.__dict__["value"] = tok
        _ct.__dict__["expires_at"] = time.monotonic() + TOKEN_TTL
        self._proxy_token = _ct
        return tok

    async def resolve(self, name: str) -> Destination:
        cached = self._dest_cache.get(name)
        if cached and time.monotonic() < cached[1]:
            return cached[0]
        creds = _first_binding("destination") or {}
        if not creds:
            raise RuntimeError("No destination service binding found in VCAP_SERVICES.")
        access_token = await self._xsuaa_access_token()
        uri = creds["uri"].rstrip("/")
        url = f"{uri}/destination-configuration/v1/destinations/{name}"
        async with httpx.AsyncClient(timeout=self._timeout) as http:
            r = await http.get(
                url,
                headers={
                    "Authorization": f"Bearer {access_token}",
                    "Accept": "application/json",
                },
            )
        if r.status_code >= 400:
            raise RuntimeError(
                f"Destination service returned {r.status_code} for {name!r}: {r.text}"
            )
        body = r.json()
        cfg = body.get("destinationConfiguration") or {}
        d_url = (cfg.get("URL") or "").rstrip("/")
        if not d_url:
            raise RuntimeError(f"Destination {name!r} has no URL configured.")
        sap_client = (cfg.get("sap-client") or cfg.get("SAP-Client") or cfg.get("sap_client"))
        well_known = {
            "URL", "Name", "Type", "Authentication", "ProxyType",
            "User", "Password", "sap-client", "SAP-Client", "sap_client",
        }
        additional = {k: v for k, v in cfg.items() if k not in well_known}
        dest = Destination(
            url=d_url,
            auth_type=cfg.get("Authentication", "NoAuthentication"),
            username=cfg.get("User"),
            password=cfg.get("Password"),
            sap_client=sap_client,
            proxy_type=cfg.get("ProxyType", "Internet"),
            additional=additional,
        )
        self._dest_cache[name] = (dest, time.monotonic() + DEST_CACHE_TTL)
        return dest

    async def proxy_settings(self) -> tuple[str, dict[str, str]]:
        creds = _first_binding("connectivity") or {}
        if not creds:
            raise RuntimeError("Destination is OnPremise but no connectivity binding found.")
        host = creds["onpremise_proxy_host"]
        port = creds["onpremise_proxy_http_port"]
        proxy_url = f"http://{host}:{port}"
        tok = await self._connectivity_proxy_token()
        return proxy_url, {"Proxy-Authorization": f"Bearer {tok}"}


class Client:
    """Async HTTP client backed by BTP destination S4Hana_QVL."""

    def __init__(
        self,
        destination = None,
        destination_name: str = DEFAULT_DESTINATION_NAME,
        timeout: float = DEFAULT_TIMEOUT_SECONDS,
        resolver = None,
    ) -> None:
        self._destination = destination
        self._destination_name = destination_name
        self._timeout = timeout
        self._resolver = resolver or _DestinationResolver(timeout=timeout)

    async def destination(self) -> Destination:
        if self._destination is None:
            self._destination = await self._resolver.resolve(self._destination_name)
        return self._destination

    def _build_url(self, base_url: str, service_path: str) -> str:
        if not service_path.startswith("/"):
            service_path = "/" + service_path
        return f"{base_url}{service_path}"

    def _auth(self, dest: Destination):
        if dest.auth_type == "BasicAuthentication" and dest.username and dest.password:
            return httpx.BasicAuth(dest.username, dest.password)
        return None

    def _base_headers(self, user_identity) -> dict[str, str]:
        h = {"Accept": "application/json"}
        if user_identity:
            h["X-User-Identity"] = user_identity
        return h

    async def _client_kwargs(self, dest: Destination) -> tuple:
        kwargs: dict[str, Any] = {"timeout": self._timeout}
        extra: dict[str, str] = {}
        if dest.proxy_type.lower() == "onpremise":
            proxy_url, hdr = await self._resolver.proxy_settings()
            kwargs["proxy"] = proxy_url
            extra.update(hdr)
        return kwargs, extra

    def _inject_mandatory_params(self, dest: Destination, params: dict) -> dict:
        if dest.sap_client and "sap-client" not in params:
            params["sap-client"] = dest.sap_client
        return params

    def _unwrap_response(self, body: Any) -> Any:
        if RESPONSE_ENVELOPE == "odata_v2" and isinstance(body, dict) and "d" in body:
            return body["d"]
        return body

    async def _fetch_csrf(self, http, dest: Destination, service_root: str, extra_headers: dict) -> str:
        params: dict[str, Any] = {}
        self._inject_mandatory_params(dest, params)
        hdr = {"x-csrf-token": "fetch", "Accept": "application/json"}
        hdr.update(extra_headers)
        r = await http.get(
            self._build_url(dest.url, service_root),
            auth=self._auth(dest), headers=hdr, params=params,
        )
        return r.headers.get("x-csrf-token") or r.headers.get("X-CSRF-Token") or ""

    async def get(
        self,
        service_path: str,
        params = None,
        user_identity = None,
    ) -> dict[str, Any]:
        dest = await self.destination()
        merged: dict[str, Any] = dict(params or {})
        self._inject_mandatory_params(dest, merged)
        client_kwargs, extra = await self._client_kwargs(dest)
        headers = self._base_headers(user_identity)
        headers.update(extra)
        async with httpx.AsyncClient(**client_kwargs) as http:
            r = await http.get(
                self._build_url(dest.url, service_path),
                auth=self._auth(dest), headers=headers, params=merged,
            )
        if r.status_code >= 400:
            return {
                "error": True, "status_code": r.status_code,
                "message": r.text, "url": self._build_url(dest.url, service_path),
            }
        try:
            body = r.json()
        except Exception:
            return {"error": True, "status_code": r.status_code, "message": r.text}
        return self._unwrap_response(body)

    async def post(
        self,
        service_path: str,
        body: dict[str, Any],
        service_root: str,
        user_identity = None,
    ) -> dict[str, Any]:
        dest = await self.destination()
        client_kwargs, extra = await self._client_kwargs(dest)
        async with httpx.AsyncClient(**client_kwargs) as http:
            csrf = ""
            if CSRF_REQUIRED:
                csrf = await self._fetch_csrf(http, dest, service_root, extra)
            headers = self._base_headers(user_identity)
            headers["Content-Type"] = "application/json"
            if CSRF_REQUIRED:
                headers["x-csrf-token"] = csrf
            headers.update(extra)
            params: dict[str, Any] = {}
            self._inject_mandatory_params(dest, params)
            r = await http.post(
                self._build_url(dest.url, service_path),
                json=body, auth=self._auth(dest), headers=headers, params=params,
            )
        if r.status_code >= 400:
            return {"error": True, "status_code": r.status_code, "message": r.text}
        try:
            return r.json()
        except Exception:
            return {"status_code": r.status_code, "raw": r.text}


__all__ = ["Client", "Destination", "DEFAULT_DESTINATION_NAME"]
